### PR TITLE
added some integration tests

### PR DESCRIPTION
**Pull request by mauro-fanton**

### CODE REVIEW

**Review by mauro-fanton — COMMENTED** [review]
I have added the License information to some source files. This is something that we may need to do for every file as iI have checked few other HMRC repo whose source file contain the license information. Usually these are added automatically for me and I don\t know how this happens, so this may be something to look into.

**Review by mpbostock — COMMENTED** [review]
Looks good to me, I recently added an exclude to the code coverage settings (CodeCoverageSettings.scala) for the documentation package (the build was failing because we didn't have 100% coverage and followed what the CTC project had done). Does the coverage only get created for the unit tests not the integration tests? I'm just wondering if we need to re-include the documentation package with these tests being added.

**Comment by mauro-fanton** [comment]
mmm, yes I think the coverage take into account the integration tests too. Just done a test, put the coverage back 100% in this PR and the coverage reach 100%. Might we want to ask if 100% coverage is too high as there may be code that does not need to be tested (have no business logic). I think HMRC require at leat 86% (but cannot be 100% sure of this), but I have see some other repo put it at 90%

**Comment by mpbostock** [comment]
> mmm, yes I think the coverage take into account the integration tests too. Just done a test, put the coverage back 100% in this PR and the coverage reach 100%. Might we want to ask if 100% coverage is too high as there may be code that does not need to be tested (have no business logic). I think HMRC require at leat 86% (but cannot be 100% sure of this), but I have see some other repo put it at 90%

Did you take out the documentation exclude I added to the [CodeCoverageSettings.scala](https://github.com/hmrc/excise-movement-control-system-api/blob/39c6212ddbaf535ea5bdc148804c268a15613d48/project/CodeCoverageSettings.scala#L10) as well as updating to 100% because otherwise that package won't be considered in the results?

**Comment by mauro-fanton** [comment]
yes, I run the tests without the integration test and did not pass the coverage. Put the integration test back and it pass the coverage

**Review by mpbostock — APPROVED** [review]
LGTM

**Pull request merged**
