### PR TITLE
Add XML schemas

### PR DESCRIPTION
**Pull request by ChrisCookOC**

### CODE REVIEW

**Review by mpbostock — CHANGES_REQUESTED** [review]
Can we just have all the `IEXXX.xsd`s and the common types that they use (tcl, tms, types, xml.xsd???). We certainly don't need all the wsdl and soap wrappers.

**Review by mpbostock — CHANGES_REQUESTED** [review]
I think if we just have a flat structure in the `xml_schemas` folder and in there we just have the ieXXX.xsd files and the tcl.xsd, tms.xsd and types.xsd. We can then generate the Scala classes from the ieXXX.xsds?? We won't be validating the messages as that's done in the EMCS Core/Stub for External test. Having the xsds here is not a risk for production as this is open source anyway and they are currently publically available and we can link to them from here in the service guide. CTC do a similar thing with their XSDs but they are stored in their validation library rather than the top level API repo.

**Comment by mpbostock** [comment]
I'm not sure if it would be better to delete this branch and start from scratch with the same branch name, you would then just add the ieXXX.xsds and force push the branch, otherwise we will be adding the other files to the Git history and then remove them in the next commit but they'll still be in the history and that will bloat the Git repo. You could also just push to a new branch with a different name but then it wouldn't be associated with this PR. I can help on this if needs be

**Comment by ChrisCookOC** [comment]
Well it seems force pushing a new branch has closed this PR anyway!

**Comment by ChrisCookOC** [comment]
New PR https://github.com/hmrc/excise-movement-control-system-api/pull/7

**Pull request closed without merging**
